name: silverblue main 40
on:
  pull_request:
  merge_group:
  schedule:
    - cron: "5 3 * * *" # 3am-ish UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      image_name: "silverblue"
      fedora_version: "40"
