name: build
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: "The name of the image to store in GHCR"
      fedora_version:
        required: true
        type: string
        description: "The version of Fedora to use"

jobs:
  build_custom:
    name: Build Silverblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Variables
        shell: bash
        run: |
          cat <<EOF >> $GITHUB_ENV
          SOURCE_IMAGE=silverblue
          SOURCE_ORG=fedora-ostree-desktops
          IMAGE_NAME=${{ inputs.image_name }}-${{ inputs.fedora_version }}
          IMAGE_REGISTRY=ghcr.io/${{ github.repository_owner }}
          FEDORA_VERSION=${{ inputs.fedora_version }}
          EOF

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          TIMESTAMP="$(date +%Y%m%d)"
          BUILD_TAGS=("latest" "${FEDORA_VERSION}")

          # Add timestamp tag for version history
          BUILD_TAGS+=("${TIMESTAMP}")

          echo "Generated the following tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done

          echo "alias_tags=${BUILD_TAGS[*]}" >> $GITHUB_OUTPUT
          echo "DEFAULT_TAG=latest" >> $GITHUB_ENV

      - name: Get current version
        id: labels
        uses: Wandalen/wretry.action@v3.5.0
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            set -eo pipefail
            ver=$(skopeo inspect docker://quay.io/${{ env.SOURCE_ORG }}/${{ env.SOURCE_IMAGE }}:${{ inputs.fedora_version }} | jq -r '.Labels["org.opencontainers.image.version"]')
            if [ -z "$ver" ] || [ "null" = "$ver" ]; then
              echo "inspected image version must not be empty or null"
              exit 1
            fi
            echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV

      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ env.SOURCE_IMAGE_VERSION }}
            org.opencontainers.image.description=Custom silverblue image.
            ostree.linux=${{ env.KERNEL_VERSION }}
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/zelf/atomic-fedora-gnome/main/os/README.md
            io.artifacthub.package.logo-url=https://avatars.githubusercontent.com/u/989504?v=4

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./os/Containerfile
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.generate-tags.outputs.alias_tags }}
          build-args: |
            IMAGE_NAME=silverblue
            SOURCE_ORG=${{ env.SOURCE_ORG }}
            SOURCE_IMAGE=${{ env.SOURCE_IMAGE }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false

      - name: Push to GHCR
        uses: Wandalen/wretry.action@v3.5.0
        id: push
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: ghcr.io
            extra-args: |
              --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v3.7.0

      - name: Sign container image
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.build_image.outputs.image }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
